Ribbon ui
spences10/VBA-IDE-Code-Export pull request #59
Opened 2017-02-22 16:18 UTC by spences10

RibbonUI with accompanying XML, thing is, now whe have to `unpack` and `pack` the `xlsm` each time we make a change to is :scream_cat: 

Appreciate your sign off here again @mattpalermo :+1:

2017-02-22 23:42 UTC, mattpalermo requested changes
Nice. I like how the XML is actually quite small for this workbook and it is possible to read through it all. It would be nice for it to be pretty printed.

The actual ribbon UI worked great and looks beautiful! Great work. I made sure that I built the workbook from the unpacked files instead of using the left over pre-built workbook in the repo just to check that it all worked. After I built the add-in and installed it into the add-ins folder, I went back and tried to rebuild another copy of the workbook (which is important for being able to build the add-in). I found that there was two indistinguishable menus in the developer tab (which is expected). However, this is not a serious problem, I quickly learnt which one was which and it worked. Unless you have a good idea of how to fix it, we can just file it as a known issue and move on.

I think the `VBA-IDE-Code-Export.xlsm` file needs to be removed from the repo since it is a duplication of the same information in the `src/VBA-IDE-Code-Export.package` directory.

Could you add some development instructions about how one would go about building the workbook and add-in from the unpacked state and also how one would go about unpacking the workbook if they wanted to commit changes made to the workbook while it was in its packed state?

I experimented with what happens when I pack the workbook, open it in Excel, press the save button, and then unpack the workbook. Pretty much every single file completely changes since the XML is all pretty much on one line (git detects changes on a line by line basis). But to my surprise, Excel didn't change one tiny bit of the CustomUI.xml file, which is good :)

Should this be merged to master or dev? Once again, I'm a bit confused about this but just wanted to raise the question.

2017-02-22 23:42 UTC, mattpalermo commented on src/VBA-IDE-Code-Export.package/customUI/customUI.xml
> +<!--RibbonX Visual Designer 1.94 for Microsoft Excel 14.0. XML Code produced on 2017/02/22-->
Does this comment serve any purpose? I know it was automagically generated, but can it be removed?

2017-02-22 23:42 UTC, mattpalermo commented on src/VBA-IDE-Code-Export.package/[Content_Types].xml
> +<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml"
Would be great to have this (I mean all the XML) pretty printed so that one might be able to read it. Is this possible?

2017-02-23 06:08 UTC, spences10 commented on src/VBA-IDE-Code-Export.package/customUI/customUI.xml
> +<!--RibbonX Visual Designer 1.94 for Microsoft Excel 14.0. XML Code produced on 2017/02/22-->
It's a comment so I 'guess' it can be removed

2017-02-23 06:10 UTC, spences10 commented on src/VBA-IDE-Code-Export.package/[Content_Types].xml
> +<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml"
Yeah, I did format it so I could have a look before committing but didn't save it, I'll take a look

2017-02-23 06:16 UTC, spences10 commented
As with #58 I'll update the readme with documentation on creating the add-in from the unpacked state. I think that this should just go into the releases as well as people may just want to download it and be done with it.

The utility to unpack/pack the XML into a workbook needs to be completed and added to the code base as well. May be a while for that though, just one thing to note the add-in used to make the ribbon menu seemed to use the same approach for packing/unpacking the XML i.e. change file extension, extract zip, edit files...

2017-02-23 07:58 UTC, mattpalermo commented
> I think that this should just go into the releases as well as people may just want to download it and be done with it.

Certainly. This will make it painless for most users. I just thought it would be friendly to let people know how to build it from source if they are looking closer at the source code. Just a simple note to let them know to put the contents of the folder into a zip and rename it.

> The utility to unpack/pack the XML into a workbook needs to be completed and added to the code base as well.

All in time. For now zipping and unzipping won't be too bad.

> just one thing to note the add-in used to make the ribbon menu seemed to use the same approach for packing/unpacking the XML i.e. change file extension, extract zip, edit files...

Seems to be the way that most programs go about modifying the spreadsheet file. If a library is used, the library is probably doing that itself.

2017-02-23 11:23 UTC, merged